'use client';

import React, { useState } from 'react';
import {
  FileText,
  Copy,
  Check,
  CheckCircle2,
  AlertCircle,
  Clock,
  Sparkles,
  RefreshCw,
  Share2,
} from 'lucide-react';
import { cn, formatDate } from '@/lib/utils';

interface HandoverProps {
  handover: any;
  projectId: string;
  onRegenerate?: () => void;
}

export default function HandoverExporter({ handover, projectId, onRegenerate }: HandoverProps) {
  const [copied, setCopied] = useState(false);
  const [checklist, setChecklist] = useState<any[]>(handover?.verificationChecklist || []);
  const [regenerating, setRegenerating] = useState(false);

  const toggleCheck = (idx: number) => {
    const updated = [...checklist];
    updated[idx].checked = !updated[idx].checked;
    setChecklist(updated);
  };

  const handleCopyMarkdown = () => {
    if (!handover) return;
    const md = `
# ${handover.title}
*Generated by AUREVEX Work Intelligence Platform on ${formatDate(handover.createdAt)}*

## Executive Summary
${handover.executiveSummary}

## Completed Milestones
${(handover.completedWork || []).map((w: string) => `- [x] ${w}`).join('\n')}

## Pending Work Items
${(handover.pendingWork || []).map((w: string) => `- [ ] ${w}`).join('\n')}

## Critical Blockers
${(handover.blockers || []).map((b: string) => `- ⚠️ ${b}`).join('\n')}

## Key Architectural Decisions
${(handover.keyDecisions || []).map((d: string) => `- 🏛️ ${d}`).join('\n')}

## Failed Approaches (Preserved Memory)
${(handover.failedApproaches || []).map((f: string) => `- 🚫 ${f}`).join('\n')}

## Recommended Next Actions
${(handover.recommendedNextSteps || []).map((s: string) => `1. ${s}`).join('\n')}

## Verification Checklist
${checklist.map((c: any) => `- [${c.checked ? 'x' : ' '}] ${c.item}`).join('\n')}
    `.trim();

    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleRegenerate = async () => {
    try {
      setRegenerating(true);
      const res = await fetch(`/api/projects/${projectId}/handover`, {
        method: 'POST',
      });
      if (res.ok && onRegenerate) {
        onRegenerate();
      }
    } catch (err) {
      console.error('Error regenerating handover:', err);
    } finally {
      setRegenerating(false);
    }
  };

  if (!handover) {
    return (
      <div className="flex flex-col items-center justify-center p-12 text-center rounded-2xl border border-dashed border-border bg-surface-card">
        <FileText className="h-10 w-10 text-slate-500 mb-3" />
        <h3 className="text-sm font-semibold text-slate-300">No Handover Generated Yet</h3>
        <p className="text-xs text-slate-500 max-w-sm mt-1">
          Synthesize all project context, architectural decisions, and current progress into an evidence-grounded transition document.
        </p>
        <button
          onClick={handleRegenerate}
          disabled={regenerating}
          className="mt-4 flex items-center gap-2 rounded-xl bg-brand-600 px-4 py-2 text-xs font-semibold text-white shadow-glow-brand hover:bg-brand-500 transition-all"
        >
          {regenerating ? <RefreshCw className="h-3.5 w-3.5 animate-spin" /> : <Sparkles className="h-3.5 w-3.5" />}
          <span>{regenerating ? 'Synthesizing...' : 'Generate Project Handover'}</span>
        </button>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Action Bar */}
      <div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-border bg-surface-card p-4">
        <div>
          <span className="rounded bg-emerald-500/20 px-2 py-0.5 text-[11px] font-mono font-bold text-emerald-300 border border-emerald-500/30">
            HANDOVER READY
          </span>
          <h2 className="text-base font-bold text-white mt-1">{handover.title}</h2>
          <span className="text-[11px] text-slate-500 font-mono">
            Synchronized at {formatDate(handover.createdAt)}
          </span>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleCopyMarkdown}
            className="flex items-center gap-1.5 rounded-lg border border-border bg-surface-raised px-3 py-1.5 text-xs font-medium text-slate-200 hover:bg-surface hover:border-slate-500 transition-all"
          >
            {copied ? <Check className="h-3.5 w-3.5 text-emerald-400" /> : <Copy className="h-3.5 w-3.5 text-slate-400" />}
            <span>{copied ? 'Copied Markdown' : 'Copy Markdown'}</span>
          </button>

          <button
            onClick={handleRegenerate}
            disabled={regenerating}
            className="flex items-center gap-1.5 rounded-lg bg-brand-600 px-3 py-1.5 text-xs font-semibold text-white hover:bg-brand-500 shadow-glow-brand transition-all disabled:opacity-50"
          >
            {regenerating ? <RefreshCw className="h-3.5 w-3.5 animate-spin" /> : <RefreshCw className="h-3.5 w-3.5" />}
            <span>{regenerating ? 'Updating...' : 'Regenerate Brief'}</span>
          </button>
        </div>
      </div>

      {/* Main Handover Content */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left 8 cols: Brief & Details */}
        <div className="lg:col-span-8 space-y-6">
          {/* Executive Summary */}
          <div className="rounded-2xl border border-border bg-surface-card p-5">
            <h3 className="text-xs font-mono font-bold uppercase tracking-wider text-brand-400">
              Executive Summary
            </h3>
            <p className="mt-2 text-xs leading-relaxed text-slate-200">
              {handover.executiveSummary}
            </p>
          </div>

          {/* Completed vs Pending Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="rounded-2xl border border-border bg-surface-card p-4 space-y-3">
              <div className="flex items-center gap-2 text-xs font-mono font-bold text-emerald-400">
                <CheckCircle2 className="h-4 w-4" />
                <span>COMPLETED WORK ({handover.completedWork?.length || 0})</span>
              </div>
              <ul className="space-y-1.5">
                {(handover.completedWork || []).map((item: string, i: number) => (
                  <li key={i} className="text-xs text-slate-300 flex items-start gap-2">
                    <span className="text-emerald-400 mt-0.5">•</span>
                    <span>{item}</span>
                  </li>
                ))}
              </ul>
            </div>

            <div className="rounded-2xl border border-border bg-surface-card p-4 space-y-3">
              <div className="flex items-center gap-2 text-xs font-mono font-bold text-amber-400">
                <Clock className="h-4 w-4" />
                <span>PENDING WORK ({handover.pendingWork?.length || 0})</span>
              </div>
              <ul className="space-y-1.5">
                {(handover.pendingWork || []).map((item: string, i: number) => (
                  <li key={i} className="text-xs text-slate-300 flex items-start gap-2">
                    <span className="text-amber-400 mt-0.5">•</span>
                    <span>{item}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {/* Key Decisions & Failed Approaches */}
          <div className="rounded-2xl border border-border bg-surface-card p-5 space-y-4">
            <h3 className="text-xs font-mono font-bold uppercase tracking-wider text-purple-400">
              Architectural Decisions & Reasoning
            </h3>
            <div className="space-y-2">
              {(handover.keyDecisions || []).map((dec: string, i: number) => (
                <div key={i} className="rounded-lg bg-surface-raised p-3 text-xs text-slate-200 border border-border">
                  {dec}
                </div>
              ))}
            </div>

            {handover.failedApproaches && handover.failedApproaches.length > 0 && (
              <div className="border-t border-border pt-4 mt-4">
                <h4 className="text-xs font-mono font-bold uppercase text-rose-400 mb-2">
                  Failed Approaches (Preserved Context)
                </h4>
                <div className="space-y-2">
                  {handover.failedApproaches.map((fa: string, i: number) => (
                    <div key={i} className="rounded-lg bg-rose-950/20 border border-rose-900/40 p-2.5 text-xs text-rose-200">
                      {fa}
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Right 4 cols: Recommended Next Steps & Verification Checklist */}
        <div className="lg:col-span-4 space-y-6">
          {/* Recommended Next Actions */}
          <div className="rounded-2xl border border-brand-500/30 bg-gradient-to-b from-brand-950/40 to-surface-card p-5 space-y-3">
            <div className="flex items-center gap-2 text-xs font-mono font-bold text-brand-300">
              <Sparkles className="h-4 w-4" />
              <span>RECOMMENDED NEXT ACTIONS</span>
            </div>
            <ol className="space-y-2.5">
              {(handover.recommendedNextSteps || []).map((step: string, i: number) => (
                <li key={i} className="text-xs text-slate-200 flex items-start gap-2">
                  <span className="font-mono text-brand-400 font-bold">{i + 1}.</span>
                  <span>{step}</span>
                </li>
              ))}
            </ol>
          </div>

          {/* Verification Checklist */}
          <div className="rounded-2xl border border-border bg-surface-card p-5 space-y-3">
            <h3 className="text-xs font-mono font-bold uppercase tracking-wider text-slate-300">
              Pre-Handover Verification Checklist
            </h3>
            <div className="space-y-2">
              {checklist.map((item: any, idx: number) => (
                <label
                  key={idx}
                  onClick={() => toggleCheck(idx)}
                  className="flex items-start gap-2.5 p-2 rounded-lg bg-surface hover:bg-surface-raised cursor-pointer border border-border transition-colors"
                >
                  <input
                    type="checkbox"
                    checked={item.checked}
                    readOnly
                    className="mt-0.5 rounded border-slate-700 text-brand-500 focus:ring-brand-500"
                  />
                  <span className={cn('text-xs leading-tight', item.checked ? 'text-slate-300' : 'text-slate-500')}>
                    {item.item}
                  </span>
                </label>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
